### PR TITLE
NEST-486: (Preview branch) Renaming EmailQuotaIndex columns and dropping index

### PR DESCRIPTION
**Pull request by wAsnk**
[NEST-486](https://lombiq.atlassian.net/browse/NEST-486)

[NEST-486]: https://lombiq.atlassian.net/browse/NEST-486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by Piedone** [comment]
This is the exact same PR as https://github.com/Lombiq/Hosting-Tenants/pull/95 just the target branch is different, right?

**Comment by wAsnk** [comment]
Yup, but this branch contains different version numbers for OC packages, so using this in DotNest. Otherwise, we would have not resolvable merge conflict.

**Comment by Piedone** [comment]
OK then. I don't think this will be needed in the end; after the merge of the other PR `dev` can be merged to `orchard-core-preview-17696`.

**Comment by wAsnk** [comment]
Sure we can do that, it was needed only for the checks. Thanks.

**Comment by Piedone** [comment]
Merged the latest dev to the preview branch after merging https://github.com/Lombiq/Hosting-Tenants/pull/95 so this is not needed.

**Pull request closed without merging**
